### ISSUE TITLE
Error choosing Team characters

### ISSUE THREAD

**Issue by AurelienEC** [Destrarion/Projet-3-OC-Jeux#1]
The loop end after 3 turns. If we enter a wrong entry ( not between 1 and 4 ) we can't have 3 characters in team.

**Comment by Tonioverzeworld** [comment]
Characters names are note unique on whole game

**Comment by Tonioverzeworld** [comment]
Change fight algorithm, for now, it's not using object oriented programming.

**Comment by Destrarion** [comment]
Problem solved by a "While countCharacter < 3 {
action
}
Thank for report !
